# Site Build Settings

# Pagination settings (v2)
pagination:
  enabled: true
  per_page: 9
  permalink: "/page/:num/"
  title: ":title - page :num"
  index_page_before: 2
  index_page_after: 2
  sort_field: "date"
  sort_reverse: true

# Build settings
markdown: kramdown
highlighter: rouge
future: true
permalink: /posts/:title/
plugins: [jekyll-paginate-v2, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

collections:
  tournaments:
    output: true
    permalink: /tournaments/:name/

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "West Country Leders"
description: "Board Gamers"
author: "Liam Mason"
hide_related_posts: true
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
